version: "3"

services:

      sonarqube_db:
        image: postgres:12.1
        networks:
           - sonar-net
        environment:
          - POSTGRES_USER=sonar
          - POSTGRES_PASSWORD=sonar
        restart: always
        container_name: sonarqube_db

      sonarqube_web:
        depends_on:
          - sonarqube_db
        image: sonarqube:7.9.1-community
        command: -Dsonar.ce.javaOpts=-Xmx1024m -Dsonar.web.javaOpts=-Xmx1024m
        ports:
          - "9000:9000"
        networks:
          - sonar-net
        environment:
          - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
          - SONARQUBE_JDBC_USERNAME=sonar
          - SONARQUBE_JDBC_PASSWORD=sonar
        restart: always
        container_name: sonarqube_web

      tomcat_web:
        image: tomcat:9.0
        ports:
          - "7778:8080"
          - "6300:6300"
        networks:
          - sonar-net
        environment:
          - JAVA_OPTS=-javaagent:/jacocoagent.jar=output=tcpserver,port=6300,address=*
        volumes:
          - ./jacoco-agent/org.jacoco.agent-0.8.7-runtime.jar:/jacocoagent.jar:ro

          
        restart: always
        container_name: tomcat_web

networks:
        sonar-net:
          driver: bridge